Use GITHUB_TOKEN in workflow.
Currently the action fails on the step for opening a PR:

```
  fatal: could not read Username for 'https://github.com': No such device or address
44
  Error: The process '/usr/bin/git' failed with exit code 128
```

https://github.com/digitalocean/digitalocean-client-python/runs/7221459241?check_suite_focus=true#step:7:47

According to https://github.com/peter-evans/create-pull-request/issues/651, that error suggests that the provided token does not have access to the repository. The builtin `GITHUB_TOKEN` one should have the permissions we need.